#!/usr/bin/python3

"""
Script to launch a Google search from the command line.
"""

import sys
import webbrowser

if len(sys.argv) > 1:
    search_terms = "+".join(sys.argv[1:])
    url = "https://www.google.com/search?q=" + search_terms 
    webbrowser.open(url)
else:
    print("Usage: python google_search.py [search terms]")
    sys.exit(1)
